# frontend:
#   image:
#     repository: nginx
#     tag: latest
#   service:
#     type: LoadBalancer
#     port: 80
#    replicaCount: 1

backend:
  image:
    repository: mpdafa/terraform-parse-service
    tag: 1.0.0
  service:
    type: LoadBalancer
    containerPort: 5000
    port: 8080
  resources:
    requests:
      cpu: 1
      memory: 256Mi
    limits:
      cpu: 2
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPU: 60